# MultiLingQuiz is part of Segimundo Ferrairó García.

# Segimundo Ferrairó García is free software: you can redistribute it and/or modify it under the terms 
# of the GNU General Public License as published by the Free Software Foundation, 
# either version 3 of the License, or (at your option) any later version.

# Segimundo Ferrairó García is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
# See the GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along with Segimundo Ferrairó García. 
# If not, see <https://www.gnu.org/licenses/>.


version: '3'
services:
  nodeapp:
    container_name: NodeJs
    build: ./NodeJs
    ports:
      - "3000:3000"
    volumes:      
      - "./NodeJs/resources:/NodeApp"
      - /NodeApp/node_modules
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      - "my-network"
  
  mongodb:
    container_name: MongoDB
    build: ./MongoDB
    ports:
      - "27017:27017"
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=my_database
    volumes:
      - "./MongoDB/db_data:/data/db"
    networks:
      - "my-network"

networks:
  my-network:
    driver: bridge